### ISSUE TITLE
Integrating State of the Art (Non DNN) Denoisers

### ISSUE THREAD

**Issue by RoyiAvital** [rengotj/cobra_denoising#1]
It seems results are very similar to Bilateral Filter with little improvement.
Does it weight close to 1?

What happens when you integrate BM3D or K-SVD?
Does the superior method get a weight of almost 1?

**Comment by rengotj** [comment]
Good afternoon.

Thank you so much for your question. This is an interesting comment. Indeed, the method is impacted by the quality of the chosen machines. As you have suggested it, states-of-the-art denoising approaches, like BM3D or K-SVD, should be used to improve the results. Their integration and the study of their impact could be done in a future work. I have just added BM3D and K-SVD machines if you want to try by yourselves.

However, I did an experiment on a small crop of the “Lena” image (in the left eye area) with multiple noise (a combination of several noise types). In this situation, the classic methods that perform best are the median filter (PSNR = 63,38) and Gaussian filter (PSNR = 63,36). The deconvolution of Richarson-Lucy has the worst performance (PSNR  = 60,29). With the original machines (“bilateral”, “nlmeans”, “gauss”, “median”, “chambolle”, “rl”, “inpaint”), our denoising method using cobra aggregation reaches a PSNR of 63,77. For this experiment the patch size is fixed to 5, the alpha parameter to 4 and the epsilon parameter to 0,2. Our model is able to detect which machines are the most relevant (the MSE of the “gauss” machine is equal to 0.014, the MSE of the “median” machine is equal to 0.017 whereas the MSE of the “rl” machine is equal to 0.072). If “ksvd” machine is added, the performances increase significantly as the obtained PSNR is equal to 64,31. 

We cannot say that the proposed method acts like the superior machine because we impose that, at least, four machines agree to select a pixel for the averaging process. All machines have a role to play, more or less important, according to the noise type met in the image.

I hope this message properly answers your question. Do not hesitate to ask for more details.  It is a pleasure to share with you about this project.

Best regards.

**Comment by RoyiAvital** [comment]
Appreciate the elaborated answer.

Basically we're dealing with fusion of estimators.
What I asked is if you take a bench of not so good estimators and one good it is likely you end up giving the good one high weight while the others are almost ignored.

Hence I asked what happens when you take a lot of classic denoisers and then add to the group advanced denoiser. Does it get the highest weight or do we have a no trivial fusion?

**Comment by bguedj** [comment]
Just to keep the ball rolling here: @RoyiAvital our Cobra algorithm averages pixel intensities, not the denoisers prediction! It is a nonlinear aggregation method and as such, delivers non-trivial fusion. If you blend several weak denoisers and a strong one, the Cobra aggregate should (slightly) outperform the collective. Even weak learners can input valuable information for some of the data patterns (as pointed out by @rengotj ).
Hope this helps! And thanks for your interest in our algorithm.

**Comment by RoyiAvital** [comment]
@bguedj , I understand the idea and I'm aware of what aggregation of learners can do. 
What I asked if you looked at the weights for the best denoiser when it is aggregated with "Weak Denoisers".

The paper doesn't show real improvement over the best in the pack.

**Comment by bguedj** [comment]
Just to clarify @RoyiAvital there is no weight per denoiser, but rather a weight per point in the (patch of the) image. The weight itself depends on denoisers. So using a strong denoiser and many weak ones will not result in one large weight and many small ones, but will rather "boosts" the consensus step and improve the overall performance.
